version: '3.8'

services:
  sidekick-dev-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,https://yourfrontend.com
      # Set DATABASE_URL to override local SQLite; otherwise defaults to sqlite:///./data/app.db
      # - DATABASE_URL=postgresql://USER:PASSWORD@HOST:PORT/DBNAME
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s